blog/urls.py
from django.contrib import admin
from django.urls import path, include
from film import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('filmler/', include("film.urls")),
    path('user/', include("user.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

film/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = "filmapp"


urlpatterns = [
    path('dasboard/', views.dasboard, name="dasboard"),
    path('addfilm/', views.addfilm, name="addfilm"),
    path('film/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.updateFilm, name="update"),
    path('delete/<int:id>', views.deleteFilm, name="delete"),
    path('', views.filmler, name="filmler"),
    path('comment/<int:id>', views.addComment, name="comment"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.userLogin, name="login"),
    path('logout/', views.userLogout, name="logout"),
]

film/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Film(models.Model):
    author = models.ForeignKey(
        "auth.User", on_delete=models.CASCADE, verbose_name="Yazar")
    title = models.CharField(max_length=65, verbose_name="Başlık")
    content = RichTextField("İçerik")
    created_date = models.DateTimeField(
        auto_now_add=True, verbose_name="Oluşturma Tarihi")
    # film_image=models.FileField(blank=True,null=True,verbose_name="Filme Resim Ekleyin")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    film = models.ForeignKey(
        Film, on_delete=models.CASCADE, verbose_name="Film", related_name="comments")
    comment_author = models.CharField(
        max_length=30, verbose_name="Ad", blank=False)
    comment_content = models.CharField(
        max_length=200, verbose_name="Yorum", blank=False)
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

film/forms.py
from django import forms
from .models import Film


class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ['title', 'content']

user/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=25, label="kullanıcı adı")
    password = forms.CharField(
        max_length=20, label="parola", widget=forms.PasswordInput)
    confirm = forms.CharField(
        max_length=20, label="parola doğrula", widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Şifreler Eşleşmiyor..")

        values = {
            "username": username,
            "password": password,
        }
        return values


class LoginForm(forms.Form):
    username = forms.CharField(label="kullanıcı adı")
    password = forms.CharField(label="parola", widget=forms.PasswordInput)

film/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .forms import FilmForm
from .models import Film, Comment
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.


def index(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")


@login_required(login_url="user:login")
def dasboard(request):
    filmler = Film.objects.filter(author=request.user)
    context = {
        "filmler": filmler
    }
    return render(request, "dasboard.html", context)


@login_required(login_url="user:login")
def addfilm(request):
    form = FilmForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        film = form.save(commit=False)

        film.author = request.user
        film.save()
        messages.success(request, "Film Oluşturuldu..")
        return redirect("index")

    return render(request, "addfilm.html", {"form": form})


def detail(request, id):
    # film = Film.objects.filter(id=id).first()

    film = get_object_or_404(Film, id=id)
    comments = film.comments.all()

    return render(request, "detail.html", {"film": film, "comments": comments})


@login_required(login_url="user:login")
def updateFilm(request, id):

    film = get_object_or_404(Film, id=id)
    form = FilmForm(request.POST or None, request.FILES or None, instance=film)

    if form.is_valid():
        film = form.save(commit=False)

        film.author = request.user
        film.save()
        messages.success(request, "Film Güncellendi..")

        return redirect("index")

    return render(request, "update.html", {"form": form})


@login_required(login_url="user:login")
def deleteFilm(request, id):

    film = get_object_or_404(Film, id=id)

    film.delete()
    messages.success(request, "Film Silindii..")

    return redirect("index")


def filmler(request):
    keyword = request.GET.get("keyword")

    if keyword:
        filmler = Film.objects.filter(title__contains=keyword)
        return render(request, "filmler.html", {"filmler": filmler})

    filmler = Film.objects.all()

    return render(request, "filmler.html", {"filmler": filmler})


def addComment(request, id):
    film = get_object_or_404(Film, id=id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        if not comment_author or not comment_content:
            messages.info(request, "Lütfen tüm alanları doldurun.")
        else:
            newComment = Comment(comment_author=comment_author,
                                 comment_content=comment_content)
            newComment.film = film
            newComment.save()

    return redirect("/filmler/film/"+str(id))

user/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib import messages
# Create your views here.

from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout


def register(request):

    form = RegisterForm(request.POST or None)
    if form.is_valid():

        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username=username)
        newUser.set_password(password)

        newUser.save()
        login(request, newUser)
        messages.success(request, ' Kayıt Olundu.. ')

        return redirect("index")

    context = {
        "form": form
    }
    return render(request, "register.html", context)


def userLogin(request):
    if request.user.is_authenticated:
        return redirect("index")
    else:
        form = LoginForm(request.POST or None)

        context = {
            "form": form
        }

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            user = authenticate(username=username, password=password)

            if user is None:
                messages.info(request, "Hatalı Kullanıcı Adı ve ya Parola")
                return render(request, "login.html", context)

            messages.success(request, "Giriş işlemi başarılı..")
            login(request, user)
            return redirect("index")

        return render(request, "login.html", context)


def userLogout(request):
    logout(request)
    messages.success(request, "Çıkış yapıldı...")
    return redirect("index")

templates/about.html
{% extends "layout.html" %} {% block body %}
<div class="jumbotron text-center">
  <h2>....Sinema Sayfam Hakkımızda....</h2>
  <hr />
  Hoş Geldiniz Film Tutkunları! Merhaba ve film dünyasının büyülü atmosferine
  hoş geldiniz! Bu film blogunda, en yeni ve en ilgi çekici filmlerden en
  unutulmaz klasiklere kadar geniş bir yelpazedeki içeriği bulacaksınız. Film
  tutkunları için tasarlanmış bu platformda, sinema sanatının derinliklerine
  dalmaya hazır olun. Sinema Sanatının Büyüsü Sinema, görsel anlatımın en
  etkileyici şeklidir. Işığın, renklerin ve sahnelerin bir araya gelerek
  öyküleri hayata geçirdiği bu sanat dalı, duygusal deneyimler sunmanın yanı
  sıra düşündürücü ve sürükleyici hikayelerin anlatılmasını sağlar. Burada, bu
  büyülü dünyanın derinliklerine bir yolculuğa çıkacaksınız. En İyi Film
  İncelemeleri Film blogumuzda, en popüler ve en yeni filmler hakkında ayrıntılı
  incelemeler bulabilirsiniz. Hangi filmin sizin için doğru seçim olduğuna karar
  verirken size rehberlik edecek değerlendirmeler ve yorumlar burada sizi
  bekliyor olacak. Ayrıca, film eleştirmenlerinin görüşleri ve izleyici
  tepkileriyle birleşen içerikler, filmleri daha yakından tanımanıza yardımcı
  olacak. Klasikler ve Kült Filmler Sinemanın altın çağlarını keşfetmek
  isteyenler için, klasiklerden kült filmlere kadar uzanan özel bir bölümümüz
  var. Unutulmaz karakterler, ikonik sahneler ve derin anlamlarla dolu bu
  filmler, sinema tarihine damgasını vurmuş yapıtlardır. Eski zamanların
  büyüsüne kapılmak ve o dönemin ruhunu yakalamak için buradayız. Sinema
  Teknolojisi ve İnovasyon Sinema sadece hikayelerle sınırlı değil, aynı zamanda
  teknolojik yeniliklerle de şekilleniyor. Film blogumuzda, sinema dünyasındaki
  en son teknolojik gelişmeleri ve yenilikleri keşfedebilirsiniz. Yeni çekim
  teknikleri, özel efektler ve dijital animasyonlar gibi konularla ilgili
  içerikler sayesinde sinemanın arkasındaki sihirli dünyayı daha iyi
  anlayacaksınız. Film Tutkunlarıyla Buluşun Film blogumuz, film tutkunları için
  bir buluşma noktasıdır. Siz de bu heyecanlı yolculuğa katılarak, favori
  filmleriniz hakkında sohbet edebilir, tartışmalara katılabilir ve en son
  sinema trendlerini takip edebilirsiniz. Sizleri film dolu bir dünyaya davet
  ediyoruz! Unutmayın, sinema herkes için bir sanattır ve bu blog, tüm film
  severlere açıktır. İyi okumalar ve iyi seyirler dileriz!
  <hr />
  <pre>İletişim için: tanerozer16@gmail.com</pre>
  <hr />
</div>
{% endblock body %}

templates/addfilm.html
{% extends "layout.html" %} {% block body %} {% load crispy_forms_tags %}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="mt-2">Yeni Film Oluştur</h2>
      <hr class="my-4" style="border-top: 3px solid #ff9900" />

      <form action="" method="POST">
        {% csrf_token %} {{ form.media }} {{ form|crispy }}
        <div class="mt-4">
          <button type="submit" class="btn btn-warning">Film Ekleyin</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock body %}

templates/dasboard.html
{% extends "layout.html" %} {% block body %}
<div class="container">
  <h2 class="my-2">Kontrol Panelim</h2>
  <hr class="my-4" style="border-top: 3px solid #ff9900" />

  <p>Hoşgeldiniz, <strong>{{ request.user.username }}</strong></p>
  <hr />

  <a href="/filmler/addfilm" class="btn btn-warning mb-4">Film Ekleyin</a>

  {% if filmler %}
  <table class="table table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Film Başlığı</th>
        <th scope="col">Yazar</th>
        <th scope="col">Yayınlama Tarihi</th>
        <th scope="col">İşlemler</th>
      </tr>
    </thead>
    <tbody>
      {% for film in filmler %}
      <tr>
        <th scope="row">{{ film.id }}</th>
        <td><a href="/filmler/film/{{ film.id }}">{{ film.title }}</a></td>
        <td>{{ film.author.username }}</td>
        <td>{{ film.created_date|date:"d F Y, H:i" }}</td>
        <td>
          <a
            href="/filmler/update/{{ film.id }}"
            class="btn btn-success btn-sm mr-2"
            >Güncelle</a
          >
          <a href="/filmler/delete/{{ film.id }}" class="btn btn-danger btn-sm"
            >Sil</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% else %}
  <div class="alert alert-danger mt-4">Henüz Film Bulunmuyor..!</div>
  {% endif %}
</div>
{% endblock body %}

templates/detail.html
{% extends "layout.html" %} {% block body %}
<div class="container">
  <div class="col-lg-12">
    <h1 class="mt-2 text-dark font-weight-bold">{{film.title}}</h1>
    <p class="lead text-muted">
      by {{film.author.username}} || {{film.created_date|date:"F d, Y H:i"}}
    </p>
    <hr class="border-top my-2" />

    {% if film.film_image.url %}
    <div class="my-4">
      <img
        class="img-fluid rounded"
        src="{{film.film_image.url}}"
        alt="{{film.title}}"
      />
    </div>
    <hr class="border-top my-4" />
    {% endif %}

    <p class="lead">{{film.content|safe}}</p>
    <hr class="my-4" style="border-top: 3px solid #ff9900" />

    <h4 class="my-4">Yorumlar</h4>
    <hr class="border-top my-4" />

    {% if comments %}
    <div class="media mb-4">
      <div class="media-body">
        {% for comment in comments %}
        <div class="media mb-4">
          <img
            src="https://placekitten.com/50/50"
            class="mr-3 rounded-circle"
            alt="{{ comment.comment_author }}"
          />
          <div class="media-body">
            <h5 class="mt-0">{{ comment.comment_author }}</h5>
            <small class="text-muted"
              >Yorum tarihi: {{ comment.comment_date }}</small
            >
            <p>{{ comment.comment_content }}</p>
          </div>
        </div>
        <hr class="border-top my-3" />
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="alert alert-danger">Bu filme henüz yorum yapılmamış.</div>
    {% endif %}

    <hr class="my-4" style="border-top: 3px solid #ff9900" />

    <div class="custom-card mt-4">
      <div class="custom-card-header">
        <h5>Yorum Ekleyin</h5>
      </div>
      <div class="custom-card-body">
        <form method="post" action="/filmler/comment/{{film.id}}">
          {% csrf_token %}
          <div class="form-group">
            <label for="comment_author">Adınız</label>
            <input
              name="comment_author"
              type="text"
              class="form-control"
              id="comment_author"
              placeholder="Adınızı girin"
            />
          </div>
          <div class="form-group">
            <label for="comment_content">Yorumunuz</label>
            <textarea
              name="comment_content"
              class="form-control"
              id="comment_content"
              rows="3"
              placeholder="Yorumunuzu buraya yazın"
            ></textarea>
          </div>
          <button type="submit" class="btn btn-warning">Yorum Ekle</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/filmler.html
{% extends "layout.html" %} {% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron text-center bg-dark text-light">
        <h1 class="display-3">Hoş Geldiniz</h1>
        <p class="lead">En iyi filmleri burada bulun!</p>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-8">
    <form class="d-flex align-items-center">
      {% csrf_token %}
      <input
        type="text"
        name="keyword"
        class="form-control me-2"
        placeholder="İstediğiniz filmi arayın..."
        aria-label="Film ara" />
      <button type="submit" class="btn btn-warning">Ara</button>
    </form>
  </div>
</div>

<div class="container">
  {% if filmler %} {% for film in filmler %}
  <div class="row">
    <div class="col-md-12">
      <!-- Post Content Column -->
      <a href="/filmler/film/{{film.id}}" class="text-decoration-none">
        <h2 class="mt-4">{{film.title}}</h2>
      </a>

      <!-- Author -->
      <p class="lead">
        <strong class="text-danger">{{film.author.username}}</strong>
        tarafından yazıldı.
      </p>

      <hr class="my-2" />

      <!-- Published Date -->
      <p class="text-muted">
        Yayınlanma Tarihi: {{film.created_date|date:"d F Y, H:i"}}
      </p>

      <hr class="my-2" />
      <!-- Preview Image -->
      <!-- {% if film.film_image %}
      <p>
        Resim Yüklenmiş: <a href="{{ film.film_image.url }}">Yüklenen Resim</a>
      </p>
      <img
        class="img-fluid rounded"
        src="{{film.film_image.url}}"
        alt="{{film.title}}" />
      {% endif %} -->

      <!-- <hr /> -->

      <!-- Post Content -->
      <p>{{ film.content|safe|truncatewords:50 }}</p>
      <div class="text-end">
        <a href="/filmler/film/{{ film.id }}" class="btn btn-sm btn-warning"
          >Devamını Oku</a
        >
      </div>
      <hr class="my-4" style="border-top: 3px solid #ff9900" />
    </div>
  </div>
  {% endfor %} {% else %}
  <div class="row">
    <div class="col-md-10">
      <div class="alert alert-danger">Henüz film bulunmamaktadır.</div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-warning   mb-4">
    <a class="navbar-brand" href="{% url 'index' %}">Film Blogum</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">Film Blogu Hakkında</span></a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="/filmler">Filmler</span></a>
        </li>

       </ul> 
      <ul class="navbar-nav ml-auto">

      {% if request.user.is_authenticated %}

        <li class="nav-item active ">
          <a class="nav-link" href="/filmler/dasboard">Panelim</span></a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</span></a>
        </li>

      {% else %}
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</span></a>
      </li>
      {% endif %}
  
      <li class="nav-item active ">
        <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</span></a>
      </li>

      

      </ul>
      
    </div>
  </nav>

templates/includes/posttemplate.html
<div class="row">
  <!-- Post Content Column -->
  <div class="col-lg-8">
    <!-- Title -->
    <h1 class="mt-4">Post Title</h1>

    <!-- Author -->
    <p class="lead">
      by
      <a href="#">Start Bootstrap</a>
    </p>

    <hr />

    <!-- Date/Time -->
    <p>Posted on January 1, 2019 at 12:00 PM</p>

    <hr />

    <!-- Preview Image -->
    <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="" />

    <hr />

    <!-- Post Content -->
    <p class="lead">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero,
      obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam
      quia corporis eligendi eos magni recusandae laborum minus inventore?
    </p>

    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur
      natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo
      dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.
    </p>

    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus,
      dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt
      ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!
    </p>

    <blockquote class="blockquote">
      <p class="mb-0">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere
        erat a ante.
      </p>
      <footer class="blockquote-footer">
        Someone famous in
        <cite title="Source Title">Source Title</cite>
      </footer>
    </blockquote>

    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum,
      aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam
      alias modi dicta saepe minima ab quo voluptatem obcaecati?
    </p>

    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor
      quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem
      voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui,
      necessitatibus, est!
    </p>

    <hr />

    <!-- Comments Form -->
    <div class="card my-4">
      <h5 class="card-header">Leave a Comment:</h5>
      <div class="card-body">
        <form>
          <div class="form-group">
            <textarea class="form-control" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>

    <!-- Single Comment -->
    <div class="media mb-4">
      <img
        class="d-flex mr-3 rounded-circle"
        src="http://placehold.it/50x50"
        alt="" />
      <div class="media-body">
        <h5 class="mt-0">Commenter Name</h5>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
        ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus
        viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
        Donec lacinia congue felis in faucibus.
      </div>
    </div>

    <!-- Comment with nested comments -->
    <div class="media mb-4">
      <img
        class="d-flex mr-3 rounded-circle"
        src="http://placehold.it/50x50"
        alt="" />
      <div class="media-body">
        <h5 class="mt-0">Commenter Name</h5>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
        ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus
        viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
        Donec lacinia congue felis in faucibus.

        <div class="media mt-4">
          <img
            class="d-flex mr-3 rounded-circle"
            src="http://placehold.it/50x50"
            alt="" />
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
            scelerisque ante sollicitudin. Cras purus odio, vestibulum in
            vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi
            vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <div class="media mt-4">
          <img
            class="d-flex mr-3 rounded-circle"
            src="http://placehold.it/50x50"
            alt="" />
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
            scelerisque ante sollicitudin. Cras purus odio, vestibulum in
            vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi
            vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Sidebar Widgets Column -->
  <div class="col-md-4">
    <!-- Search Widget -->
    <div class="card my-4">
      <h5 class="card-header">Search</h5>
      <div class="card-body">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for..." />
          <span class="input-group-append">
            <button class="btn btn-secondary" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>

    <!-- Categories Widget -->
    <div class="card my-4">
      <h5 class="card-header">Categories</h5>
      <div class="card-body">
        <div class="row">
          <div class="col-lg-6">
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#">Web Design</a>
              </li>
              <li>
                <a href="#">HTML</a>
              </li>
              <li>
                <a href="#">Freebies</a>
              </li>
            </ul>
          </div>
          <div class="col-lg-6">
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#">JavaScript</a>
              </li>
              <li>
                <a href="#">CSS</a>
              </li>
              <li>
                <a href="#">Tutorials</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- Side Widget -->
    <div class="card my-4">
      <h5 class="card-header">Side Widget</h5>
      <div class="card-body">
        You can put anything you want inside of these side widgets. They are
        easy to use, and feature the new Bootstrap 4 card containers!
      </div>
    </div>
  </div>
</div>

templates/index.html
{% extends "layout.html" %} {% block body %}

<div class="jumbotron text-center bg-dark text-light">
  <h1 class="display-3">Sinema Dünyasına Hoş Geldiniz</h1>
  <p class="lead">
    Sinema tutkunlarının buluşma noktasına hoş geldiniz! En yeni filmleri
    kapsamlı incelemelerle keşfedin. Kendi görüşlerinizi paylaşın ve diğer
    sinema meraklılarının yorumlarını okuyun. Sinema dünyasındaki son
    gelişmeleri takip etmek için bizi düzenli olarak ziyaret edin. Ayrıca, özel
    film etkinlikleri ve haberleri hakkında bilgi sahibi olun.
  </p>
</div>

{% endblock body %}

templates/layout.html
{% load static %}
{% load tz %}
{% now "Y" as current_year %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
            background: linear-gradient( #ecb7bd, #ddf37b);
            margin-bottom: 150px;
            margin-top: 75px;
        }
    </style>
</head>
<body>
    <div class="container">
        {% include "includes/navbar.html" %}
        {% if messages %}
            {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <br><br><br>
        <div class="container">
            {% block body %} 
            {% endblock %}
        </div>
    </div>

    <hr class="my-4" style="border-top: 10px solid #ff9900" />

    <footer class="footer mt-auto py-3">
        <div class="container">
            <span class="text-muted">
                Film Blogum &copy; {{ current_year }} -
                <a href="https://github.com/dxtaner" target="_blank">@dxtaner </a>
                Tarafından yapıldı
            </span>
        </div>
    </footer>


    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>